{% set name = "ecgtools" %}
{% set version = "2024.7.31" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ecgtools-{{ version }}.tar.gz
  sha256: 3111972388ac2f04f84de1e1a5b40596d131d1ea2dd675a1cce50433b8bb5c3e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=30.3.0
    - setuptools_scm
  run:
    - cf_xarray
    - dask-core
    - joblib
    - netcdf4
    - pandas
    - pydantic
    - python >=3.8
    - pyyaml
    - typer
    - xarray
    - intake-esm >=2022

test:
  imports:
    - ecgtools
    - ecgtools.parsers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ncar-xdev/ecgtools
  summary: ESM Catalog Generation Utilities
  dev_url: https://github.com/ncar-xdev/ecgtools
  doc_url: https://ecgtools.readthedocs.io/en/latest/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgrover1
    - andersy005
