{% set name = "ecgtools" %}
{% set version = "2021.9.23" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ecgtools-{{ version }}.tar.gz
  sha256: de1b72d046757331929f79574595d97b3a03fe66b0d3788f19b862712d5849c5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=30.3.0
    - setuptools_scm
  run:
    - cf_xarray
    - dask-core
    - joblib
    - netcdf4
    - pandas
    - pydantic
    - python >=3.7
    - pyyaml
    - typer
    - xarray

test:
  imports:
    - ecgtools
    - ecgtools.parsers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NCAR/ecgtools
  summary: ESM Catalog Generation Utilities
  dev_url: https://github.com/NCAR/ecgtools
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgrover1
    - andersy005
